### ISSUE TITLE
Use case diagram

### ISSUE THREAD

**Issue by Christian13341767** [wbYAN/UTS-Collaboration-Group-7#10]

**Comment by xingpeifeng** [comment]
![image](https://user-images.githubusercontent.com/48883393/82631296-7d268700-9c38-11ea-9624-115a62a21d92.png)

**Comment by wbYAN** [comment]
![image](https://user-images.githubusercontent.com/62375572/83327399-d2107000-a2be-11ea-94f6-9f05146f132e.png)

**Comment by wbYAN** [comment]
![image](https://user-images.githubusercontent.com/62375572/83327401-d9d01480-a2be-11ea-8c24-827bbfcea0d1.png)
