### ISSUE TITLE
Competitive advantages and possible effects if the project fails

### ISSUE THREAD

**Issue by xingpeifeng** [wbYAN/UTS-Collaboration-Group-7#11]

**Comment by xingpeifeng** [comment]
advantages: This in-house call management centre (CMC) system can increase the efficency of calls by accurating positioning of customers. And also reduce the cost like decreasing the potenial telephone charge and saving the cost and the time of transportation for employees to get to work. Due to creating the customer profile, it is easier for RM to be aware of what the customers might want. Due to the more reasonable matching between the customer and the RM, the customer's satisfaction with the RM will increase, which is also more conducive for the RM to obtain more potential demands from the customer during the call.It would be a virtuous circle. In addition, the customer's rating system will also make customers more enthusiastic to buy, purchasing more items will improve their scores, so as to get better service. Similarly for RM, they will be more active in customer service and strive to improve their experience and expertise.

**Comment by wbYAN** [comment]
Pros 
- Automated system of matching customers to a relationship manager with better skill matcher using Profiler Tool.
 - Help customers to manage their time better to prevent wasting time by allowing them to book a call with a relationship manager.
- Save costs by making effective outbound calls using a target list generated from the system where guides are shown to the relationship manager of which holiday packages suit the customer well.

Cons 
    -   If the profiler tool went down, the whole call operations will not run due to being unable to match a customer to a relationship manager.
      - Customer and relationship manager profiles might be stolen or leaked to unauthorized people.
