### ISSUE TITLE
Objective and define the problem 

### ISSUE THREAD

**Issue by wbYAN** [wbYAN/UTS-Collaboration-Group-7#4]

**Comment by Christian13341767** [comment]
Objective improve the operation of in-house call management centre and adjust the call flow rate for the relationship managers

**Comment by Christian13341767** [comment]
RM problem:  RMs have insufficient information on the customer to provide the best matching sale or service.

**Comment by Christian13341767** [comment]
Problem2: RM and customer's matching technique are not efficient.

**Comment by xingpeifeng** [comment]
Customer problem: during the busy time, the customer may wait a long time so they hang up
