### ISSUE TITLE
Empathy map 

### ISSUE THREAD

**Issue by wbYAN** [wbYAN/UTS-Collaboration-Group-7#5]
Please draw empathy map for customer and RM （Everyone）
We will discuss and compare it on Thursday 14/5 or before . Tq!

**Comment by xingpeifeng** [comment]
OK   thanks very much


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: wbYAN <notifications@github.com>
发送时间: Friday, May 8, 2020 2:59:24 PM
收件人: wbYAN/UTS-Collaboration-Group-7 <UTS-Collaboration-Group-7@noreply.github.com>
抄送: Peifeng Xing <Peifeng.Xing-1@student.uts.edu.au>; Assign <assign@noreply.github.com>
主题: [wbYAN/UTS-Collaboration-Group-7] Empathy map (#5)


Please draw empathy map for customer and RM （Everyone）
We will discuss and compare it on Thursday 14/5 or before . Tq!

―

**Comment by wbYAN** [comment]
I suggest you all to use the empathy map template provided under tutorial file

**Comment by wbYAN** [comment]
Please upload it under branch: develop not master
