### ISSUE TITLE
Stage 2: POV statement

### ISSUE THREAD

**Issue by wbYAN** [wbYAN/UTS-Collaboration-Group-7#6]
Please come out with some POV statement for stage 2 (Define) of design thinking. Could refer from lecture 3

**Comment by Christian13341767** [comment]
•	Customer who are from different background would purchase holiday packages from the travel company to have a trip that is organized and planned. However, some of the holiday packages might not attract them. 
•	Customer who want to purchase the holiday package introduced will call the RM to receive additional information and details about the packages. However, long wait time to approach a RM cause the customer hang up the call. 
•	Customer who want to know more about the holiday packages by calling the RM to receive more information about the holiday packages. Unfortunately, the RM did not have sufficient knowledge which make the customer turned down the call.  
•	RM of the travel company will call potential customers to sell their holiday packages but most of the calls are rejected. 
•	RM of the travel company will call potential customers to sell their holiday packages, but the customer does not speak the same languages.

**Comment by Christian13341767** [comment]
•	Customers with lower score will have to wait

**Comment by Christian13341767** [comment]
Customer who suffer a long time for their calls to be taken usually hang up.
