### ISSUE TITLE
Reflection (Include assumptions)

### ISSUE THREAD

**Issue by Christian13341767** [wbYAN/UTS-Collaboration-Group-7#7]

**Comment by xingpeifeng** [comment]
Assumpt the customer score is 0 to 10. We can give the new customer a higher score like 7 or 8. And then, increase or decrease his or her score according to his purchasing power or some other attributes. This can avoid the new customer may wait a long time due to his lower origianl score.

**Comment by Christian13341767** [comment]
customers are lacking the motivation to take calls from RMs promoting irrelevant deals.

**Comment by wbYAN** [comment]
RM wasted a lot of time making calls to potential customers

**Comment by Christian13341767** [comment]
Customers are concerned about call scams which cause customers to not take outbound calls.

**Comment by xingpeifeng** [comment]
Customer are concerned about the security of their privacy information that they have provided to create the  Profiler Tool.

**Comment by wbYAN** [comment]
Customer might not speak the same language with the RM
