### ISSUE TITLE
HMW statements

### ISSUE THREAD

**Issue by Christian13341767** [wbYAN/UTS-Collaboration-Group-7#8]

**Comment by wbYAN** [comment]
![image](https://user-images.githubusercontent.com/62375572/82552481-89153900-9ba5-11ea-8014-1a66d4c18ce9.png)

**Comment by wbYAN** [comment]
![image](https://user-images.githubusercontent.com/62375572/82555717-a2b97f00-9bab-11ea-965b-8af47531c426.png)
