### ISSUE TITLE
User Stories 

### ISSUE THREAD

**Issue by wbYAN** [wbYAN/UTS-Collaboration-Group-7#9]

**Comment by Christian13341767** [comment]
As a customer, I want a higher customer score so that I can get service faster.

**Comment by Christian13341767** [comment]
As a relationship manager, I want more information about the customer so that I can give the most suitable deals for them.

**Comment by wbYAN** [comment]
As a customer, I want a knowledgeable relationship manager to answer my call so that i can get a right and value deals.

**Comment by xingpeifeng** [comment]
As a customer, I want my information to be visible only to the relevant RM so that I can make my information secure.

**Comment by Christian13341767** [comment]
As a relationship manager, I want to make more sales to the customers so that I can get more incentives.

**Comment by wbYAN** [comment]
As a customer, I want my trips planned and organized well so that I can have a nice experience.
As a customer, I want my trips safe so that I can enjoy my holidays. 
As a RM, I want to promote the best travel package to my customer so that I can make a sale. 
As a RM, I want my customer to respect me so that I can serve them better 
As a customer, I want my call to be answered as soon as possible so that I will not hang up the call

**Comment by wbYAN** [comment]
As a RM, I want to answer the calls from customers as soon as possible so that I will not lose any potential customers.

**Comment by wbYAN** [comment]
As a customer, I want RM, who contacted me to have the same background as me so that misunderstanding can be avoided. 
As a RM, I want to have more colleagues so that all calls from customers will be answered. 
As a RM, I want to learn more about other cultures so that I could understand customers with different backgrounds.

**Comment by wbYAN** [comment]
As a RM, I want to make sure that I will only give accurate and real information to customers so that they will not receive false information.

**Comment by wbYAN** [comment]
As a Rm, I want to make sure that the customer understands what the travel package contains so that they will not make compliant afterward.

**Comment by xingpeifeng** [comment]
As a RM, I want my phone bill can be reimbursed by my company so that I can save much money.

**Comment by wbYAN** [comment]
1. As a relationship manager, I want more information about the customer so that I can give the most suitable deals for them.
2. As a customer, I want my call to be answered as soon as possible so that I will not hang up the call
3. As a customer, I want a knowledgeable relationship manager to answer my call so that i can get a right and value deals.
4. As a RM, I want to promote the best travel package to my customer so that I can make a sale.
5. As a customer, I want a higher customer score so that I can get service faster.

**Comment by xingpeifeng** [comment]
1.As a relationship manager, I want more information about the customer so that I can give the most suitable deals for them.
2.As a relationship manager, I want to make more sales to the customers so that I can get more incentives.
3.As a customer, I want a higher customer score so that I can get service faster.
4.As a customer, I want a knowledgeable relationship manager to answer my call so that i can get a right and value deals.
